# Generated by Django 4.2.2 on 2024-04-04 05:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.CharField(max_length=5, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('college_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('mentor_name', models.CharField(blank=True, default='', max_length=255)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('certificate_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='certificate_app.certificatetypes')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRelatedAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='certificatetypes',
            name='courses',
            field=models.ManyToManyField(related_name='certificate_types', to='certificate_app.course'),
        ),
    ]
