# Generated by Django 4.2.2 on 2024-03-07 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('embedded system', 'Embedded System'), ('python fullstack', 'Python Fullstack'), ('AI & ML', 'Artificial Intelligence & Machine learning'), ('data science', 'Data Science'), ('Digital marketing', 'Digital marketing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(max_length=255),
        ),
    ]
