# Generated by Django 4.2.2 on 2024-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_student_start_date_alter_student_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('embedded system', 'Embedded System'), ('python fullstack', 'Python Fullstack'), ('AI & ML', 'Artificial Intelligence & Machine learning'), ('data science', 'Data Science'), ('Digital marketing', 'Digital marketing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
