# Generated by Django 4.2.2 on 2024-04-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_alter_authority_authority_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='authority_id',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
