# Generated by Django 4.2.2 on 2024-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0005_alter_student_college_name_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(blank=True, default='Default College Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('embedded_system', 'Embedded System'), ('python_fullstack', 'Python Fullstack'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('data_science', 'Data Science'), ('digital_marketing', 'Digital Marketing')], default='Default Curse Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, default='Default Mentor Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='Default  Name', max_length=255),
        ),
    ]
