# Generated by Django 4.2.2 on 2024-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0006_student_created_at_alter_authority_authority_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='authority_id',
            new_name='auth_id',
        ),
        migrations.AddField(
            model_name='certificatetypes',
            name='certify_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
