# Generated by Django 4.2.2 on 2024-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0007_alter_student_college_name_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('embedded system', 'Embedded System'), ('python fullstack', 'Python Fullstack'), ('AI & ML', 'Artificial Intelligence & Machine Learning'), ('data science', 'Data Science'), ('digital marketing', 'Digital Marketing')], default='', max_length=100),
        ),
    ]
