# Generated by Django 4.2.2 on 2024-04-16 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0008_alter_student_certificate_type_alter_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('sem_year', models.CharField(blank=True, default='', max_length=100)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('college_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.CharField(blank=True, default='', max_length=255)),
                ('mentor_name', models.CharField(blank=True, default='', max_length=255)),
                ('conducted_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.certificatetypes')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.course')),
            ],
        ),
    ]
