# Generated by Django 4.2.2 on 2024-03-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0009_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='signature',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
