# Generated by Django 4.2.2 on 2024-04-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0009_studentiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrelatedauthority',
            name='std_iv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studentiv'),
        ),
    ]
