# Generated by Django 4.2.2 on 2024-03-27 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0010_alter_authority_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
