# Generated by Django 4.2.2 on 2024-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0010_studentrelatedauthority_std_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentiv',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
