# Generated by Django 4.2.2 on 2024-04-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0011_alter_studentiv_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority'),
        ),
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.student'),
        ),
    ]
