# Generated by Django 4.2.2 on 2024-03-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0011_student_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authority',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority'),
        ),
    ]
