# Generated by Django 4.2.2 on 2024-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0012_alter_studentrelatedauthority_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentiv',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
