# Generated by Django 4.2.2 on 2024-03-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0012_student_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='authority',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority'),
        ),
    ]
