# Generated by Django 4.2.2 on 2024-05-02 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0013_student_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tronix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('events', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
