# Generated by Django 4.2.2 on 2024-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0015_alter_student_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
