# Generated by Django 4.2.2 on 2024-05-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0016_alter_certificatetypes_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttronix',
            name='certificate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.certificatetypes'),
        ),
        migrations.AlterField(
            model_name='certificatetypes',
            name='courses',
            field=models.ManyToManyField(related_name='certificate_types', to='certificate_app.course'),
        ),
    ]
