# Generated by Django 4.2.2 on 2024-05-02 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0017_studenttronix_certificate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttronix',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studenttronix',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studenttronix',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
