# Generated by Django 4.2.2 on 2024-05-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0018_studenttronix_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrelatedauthority',
            name='std_tronix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studenttronix'),
        ),
    ]
