# Generated by Django 4.2.2 on 2024-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0018_alter_student_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='authority',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
