# Generated by Django 4.2.2 on 2024-05-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0019_studentrelatedauthority_std_tronix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tronix_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tronix',
            name='event',
        ),
        migrations.DeleteModel(
            name='Tronix_events',
        ),
        migrations.AddField(
            model_name='tronix',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.tronix_items'),
        ),
    ]
