# Generated by Django 4.2.2 on 2024-03-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0019_alter_authority_name_alter_authority_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='authority',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='certificate_app.authority'),
        ),
    ]
