# Generated by Django 4.2.2 on 2024-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0020_tronix_items_remove_tronix_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttronix',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
