# Generated by Django 4.2.2 on 2024-05-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0021_studenttronix_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tronix',
            name='place',
        ),
        migrations.AddField(
            model_name='studenttronix',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
