# Generated by Django 4.2.2 on 2024-05-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0022_remove_tronix_place_studenttronix_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tronix_items',
            new_name='TronixItems',
        ),
    ]
