# Generated by Django 4.2.2 on 2024-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0023_rename_tronix_items_tronixitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='media/partners/')),
            ],
        ),
        migrations.AddField(
            model_name='tronix',
            name='partner_logos',
            field=models.ManyToManyField(to='certificate_app.partner'),
        ),
    ]
