# Generated by Django 4.2.2 on 2024-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0024_partner_tronix_partner_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tronix',
            name='height',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='tronix',
            name='width',
            field=models.FloatField(default=100),
        ),
    ]
