# Generated by Django 4.2.2 on 2024-03-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0025_course_certificatetype_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='authority',
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='authority',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='certificate_app.authority'),
        ),
    ]
