# Generated by Django 4.2.2 on 2024-05-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0026_alter_tronix_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tronix',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tronix',
            name='width',
        ),
        migrations.AddField(
            model_name='partner',
            name='height',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='width',
            field=models.FloatField(default=100),
        ),
    ]
