# Generated by Django 4.2.2 on 2024-05-17 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0028_alter_partner_height_alter_partner_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('college_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('mentor_name', models.CharField(blank=True, default='', max_length=255)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='certificate_app.certificatetypes')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='certificate_app.course')),
            ],
        ),
    ]
