# Generated by Django 4.2.2 on 2024-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0028_remove_student_authority_certificatetype_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetype',
            name='authority',
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='authorities',
            field=models.ManyToManyField(related_name='certificate_types', to='certificate_app.authority'),
        ),
    ]
