# Generated by Django 4.2.2 on 2024-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0029_remove_certificatetype_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='authorities',
            field=models.ManyToManyField(null=True, related_name='certificate_types', to='certificate_app.authority'),
        ),
    ]
