# Generated by Django 4.2.2 on 2024-05-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0029_studentworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrelatedauthority',
            name='std_workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studentworkshop'),
        ),
    ]
