# Generated by Django 4.2.2 on 2024-06-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0030_studentrelatedauthority_std_workshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetypes',
            options={'verbose_name': 'Certificate Types', 'verbose_name_plural': 'Certificate Types'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Courses of Certificates', 'verbose_name_plural': 'Courses of Certificates'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student Internship Data', 'verbose_name_plural': 'Student Internship Data'},
        ),
        migrations.AlterModelOptions(
            name='studentiv',
            options={'verbose_name': 'Student IV Data', 'verbose_name_plural': 'Student IV Data'},
        ),
        migrations.AlterModelOptions(
            name='studenttronix',
            options={'verbose_name': 'Student Tronix Data', 'verbose_name_plural': 'Student Tronix Data'},
        ),
        migrations.AlterModelOptions(
            name='studentworkshop',
            options={'verbose_name': 'Student Workshop Data', 'verbose_name_plural': 'Student Workshop Data'},
        ),
        migrations.AlterModelOptions(
            name='tronix',
            options={'verbose_name': 'Tronix Certificate ', 'verbose_name_plural': 'Tronix Certificate'},
        ),
        migrations.AlterModelOptions(
            name='tronixitems',
            options={'verbose_name': 'Tronix items', 'verbose_name_plural': 'Tronix Items'},
        ),
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.student'),
        ),
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='std_tronix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studenttronix'),
        ),
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='std_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studentworkshop'),
        ),
    ]
