# Generated by Django 4.2.2 on 2024-06-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0031_alter_certificatetypes_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='digital_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentrelatedauthority',
            name='std_iv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.studentiv'),
        ),
    ]
