# Generated by Django 4.2.2 on 2024-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0032_alter_certificatetypes_authorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authorities',
            field=models.ManyToManyField(related_name='students', to='certificate_app.authority'),
        ),
    ]
