# Generated by Django 4.2.2 on 2024-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0033_student_authorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetypes',
            name='courses',
            field=models.ManyToManyField(related_name='certificate_types', to='certificate_app.course'),
        ),
    ]
