# Generated by Django 4.2.2 on 2024-04-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0034_alter_certificatetypes_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='authorities',
        ),
    ]
