# Generated by Django 4.2.2 on 2024-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0036_certificatetypes_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authorities',
            field=models.ManyToManyField(related_name='students', to='certificate_app.authority'),
        ),
    ]
