# Generated by Django 4.2.2 on 2024-04-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0037_student_authorities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='authorities',
        ),
        migrations.AddField(
            model_name='student',
            name='authorities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='certificate_app.authority'),
        ),
    ]
