# Generated by Django 4.2.2 on 2024-04-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0038_remove_student_authorities_student_authorities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetypes',
            name='signed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='authorities',
        ),
        migrations.AddField(
            model_name='student',
            name='authorities',
            field=models.ManyToManyField(related_name='students', to='certificate_app.authority'),
        ),
    ]
