# Generated by Django 4.2.2 on 2024-04-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0040_certificatetypes_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetypes',
            name='signed',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority'),
        ),
    ]
