# Generated by Django 4.2.2 on 2024-04-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0042_alter_certificatetypes_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetypes',
            name='signed',
        ),
    ]
