# Generated by Django 4.2.2 on 2024-04-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0043_remove_certificatetypes_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRelatedAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.course')),
            ],
        ),
    ]
