# Generated by Django 4.2.2 on 2024-04-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0044_courserelatedauthority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRelatedAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.authority')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='authorities',
        ),
        migrations.DeleteModel(
            name='CourseRelatedAuthority',
        ),
        migrations.AddField(
            model_name='studentrelatedauthority',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.student'),
        ),
    ]
