# Generated by Django 4.2.2 on 2024-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0047_remove_certificatetypes_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetypes',
            name='courses',
        ),
        migrations.AddField(
            model_name='certificatetypes',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='certificate_types', to='certificate_app.course'),
        ),
    ]
