# Generated by Django 4.2.2 on 2024-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0048_remove_certificatetypes_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='authority_id',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
